# Main configuration file for mkdocs generation of klipper3d.org website

# Site and directory configuration
site_name: Klipper documentation
repo_url: https://github.com/KevinOConnor/klipper
repo_name: KevinOConnor/klipper
edit_uri: blob/master/docs/
use_directory_urls: False
docs_dir: '../'
site_dir: '../../site/'

# Markdown document translation settings
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 6
  - attr_list
  - mdx_partial_gfm
  - mdx_truly_sane_lists
  - mdx_breakless_lists
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: "docs._klipper3d.mkdocs_hooks:transform"
  - exclude:
      glob:
        - README.md

# Website layout configuration (using mkdocs-material theme)
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: img/klipper.svg
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
      #- navigation.tabs
      #- navigation.expand
      - navigation.top
      # if enabled, the TOC doesn't work for some pages
      # - toc.integrate
      - search.suggest
      - search.highlight
      - search.share
extra_css:
  - _klipper3d/css/extra.css

# Site usage statistics
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#site-search-tracking
  analytics:
    provider: google
    property: UA-138371409-1

# Navigation hierarchy (this should mimic the layout of Overview.md)
nav:
  - Overview.md
  - Features.md
  - FAQ.md
  - Releases.md
  - Config_Changes.md
  - Contact.md
  - Installation and Configuration:
    - Installation.md
    - Configuration Reference:
      - Config_Reference.md
      - Rotation_Distance.md
    - Config_checks.md
    - Bed Level:
      - Bed_Level.md
      - Delta_Calibrate.md
      - Probe_Calibrate.md
      - BLTouch.md
      - Manual_Level.md
      - Bed_Mesh.md
      - Endstop_Phase.md
    - Resonance Compensation:
      - Resonance_Compensation.md
      - Measuring_Resonances.md
    - Pressure_Advance.md
    - Slicers.md
    - Command templates:
      - Command_Templates.md
      - Status_Reference.md
    - TMC_Drivers.md
    - skew_correction.md
    - Using_PWM_Tools.md
    - G-Codes.md
  - Developer Documentation:
    - Code_Overview.md
    - Kinematics.md
    - Protocol.md
    - API_Server.md
    - MCU_Commands.md
    - CANBUS_protocol.md
    - Debugging.md
    - Benchmarks.md
    - CONTRIBUTING.md
    - Packaging.md
  - Device Specific Documents:
    - Example_Configs.md
    - SDCard_Updates.md
    - RPi_microcontroller.md
    - beaglebone.md
    - Bootloaders.md
    - CANBUS.md
    - TSL1401CL_Filament_Width_Sensor.md
    - HallFilamentWidthSensor.md
  - 简体中文:
    - locales/zh-hans/Overview.md
    - locales/zh-hans/Features.md
    - locales/zh-hans/FAQ.md
    - locales/zh-hans/Releases.md
    - locales/zh-hans/Config_Changes.md
    - locales/zh-hans/Contact.md
    - Installation and Configuration:
      - locales/zh-hans/Installation.md
      - Configuration Reference:
        - locales/zh-hans/Config_Reference.md
        - locales/zh-hans/Rotation_Distance.md
      - Config_checks.md
      - Bed Level:
        - locales/zh-hans/Bed_Level.md
        - locales/zh-hans/Delta_Calibrate.md
        - locales/zh-hans/Probe_Calibrate.md
        - locales/zh-hans/BLTouch.md
        - locales/zh-hans/Manual_Level.md
        - locales/zh-hans/Bed_Mesh.md
        - locales/zh-hans/Endstop_Phase.md
      - Resonance Compensation:
        - locales/zh-hans/Resonance_Compensation.md
        - locales/zh-hans/Measuring_Resonances.md
      - locales/zh-hans/Pressure_Advance.md
      - locales/zh-hans/Slicers.md
      - Command templates:
        - locales/zh-hans/Command_Templates.md
        - locales/zh-hans/Status_Reference.md
      - locales/zh-hans/TMC_Drivers.md
      - locales/zh-hans/skew_correction.md
      - locales/zh-hans/Using_PWM_Tools.md
      - locales/zh-hans/G-Codes.md
    - Developer Documentation:
      - locales/zh-hans/Code_Overview.md
      - locales/zh-hans/Kinematics.md
      - locales/zh-hans/Protocol.md
      - locales/zh-hans/API_Server.md
      - locales/zh-hans/MCU_Commands.md
      - locales/zh-hans/CANBUS_protocol.md
      - locales/zh-hans/Debugging.md
      - locales/zh-hans/Benchmarks.md
      - locales/zh-hans/CONTRIBUTING.md
      - locales/zh-hans/Packaging.md
    - Device Specific Documents:
      - locales/zh-hans/Example_Configs.md
      - locales/zh-hans/SDCard_Updates.md
      - locales/zh-hans/RPi_microcontroller.md
      - locales/zh-hans/beaglebone.md
      - locales/zh-hans/Bootloaders.md
      - locales/zh-hans/CANBUS.md
      - locales/zh-hans/TSL1401CL_Filament_Width_Sensor.md
      - locales/zh-hans/HallFilamentWidthSensor.md
